public class IglooConstants {
  public static String ENCODING_SCHEME = 'UTF-8';
    public static String SESSION_KEY = 'sessionKey';
    public static String SECRET_KEY = 'secretKey';
    public static String API_VERSION = '1';
    public static String API_ID = 'fa268e11-5e32-401b-9dec-21e6fe21051d';
    public static String API_PASS = 'plain-island-provide-standard';
    public static String GET_METHOD = 'GET';
    public static String POST_METHOD = 'POST';
}